### ISSUE TITLE
Possible Mistake

### ISSUE THREAD

**Issue by LucasSD** [lukasfinxter/finxterinsta#1]
Hi there. Love Finxter! This is one of the questions, also featured on the blog https://blog.finxter.com/daily-python-puzzle-recursion/?unapproved=3825&moderation-hash=188c08e2c17557ff51c47deb0b96f0c5#comment-3825.

When I originally looked at this puzzle, I thought the answer should be 0. When I run the code in Thonny I get 0 as well. 

I am a newbie so there is a big chance I have made a mistake, but can you check what the answer should be please?

Thanks
Lucas

**Comment by lukasfinxter** [comment]
Hey Lucas,

this is Lukas from Finxter, thank you for your message!
I guess the problem is that the code’s indentation is broken.
I send you a picture of the correctly formatted code - maybe this clarifies your doubts.
If not, don’t hesitate to write again:)

Cheers,

Lukas

**Comment by LucasSD** [comment]
Perfect thank you!
